modLoader="javafml"
loaderVersion="[53,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="iceberg"
version="${version}"
displayName="Iceberg"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/520110"
logoFile="icon.png"
authors="Grend, Mat0u5"
description="A library containing events, helpers, and utilities to make modding easier."

[[dependencies.iceberg]]
	modId="forge"
	mandatory=true
	versionRange="[65,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="minecraft"
	mandatory=true
	versionRange="[26.2,)"
	ordering="NONE"
	side="BOTH"

[modproperties.iceberg]
	configuredProviders=[
		"com.anthonyhilyard.iceberg.compat.configured.IcebergConfigProvider"
	]