modLoader="javafml"
loaderVersion="[51,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="iceberg"
version="${version}"
displayName="Iceberg"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/520110"
logoFile="icon.png"
authors="Grend"
description="A library containing events, helpers, and utilities to make modding easier."

[[dependencies.iceberg]]
	modId="forge"
	mandatory=true
	versionRange="[51,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="advancementplaques"
	mandatory=false
	versionRange="[1.6.3,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="legendarytooltips"
	mandatory=false
	versionRange="[1.4.10,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="equipmentcompare"
	mandatory=false
	versionRange="[1.3.11,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="merchantmarkers"
	mandatory=false
	versionRange="[1.3.4,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="itemborders"
	mandatory=false
	versionRange="[1.2.4,)"
	ordering="BEFORE"
	side="BOTH"

[modproperties.iceberg]
	configuredProviders=[
		"com.anthonyhilyard.iceberg.compat.configured.IcebergConfigProvider"
	]