# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
name=Iceberg
group=com.anthonyhilyard.iceberg
author=anthonyhilyard
modVersion=1.4.1.1
enabledPlatforms=fabric,forge,neoforge
fabric.loom.disableRemappedVariants=true

# Minecraft properties
minecraftVersion=26.1.2

# Dependencies
fabricLoaderVersion=0.19.2
fabricVersion=0.149.1+26.1.2
forgeVersion=26.1.2-64.0.8
neoforgeVersion=26.1.2.66-beta
nightconfigVersion=3.6.4
