# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
name=Iceberg
group=com.anthonyhilyard.iceberg
author=anthonyhilyard
modVersion=1.4.3
enabledPlatforms=fabric,neoforge
#enabledPlatforms=fabric,forge,neoforge
fabric.loom.disableRemappedVariants=true

# Minecraft properties
minecraftVersion=26.3

# Dependencies
fabricLoaderVersion=0.19.5
forgeVersion=26.2-65.0.0
fabricVersion=0.160.7+26.3
neoforgeVersion=26.3.0.4-beta
nightconfigVersion=3.6.4
