modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved."

[[mods]]
modId="iceberg"
version="${version}"
displayName="Iceberg"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/520110"
logoFile="icon.png"
authors="Grend"
description="A library containing events, helpers, and utilities to make modding easier."

[[dependencies.iceberg]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5]"
	ordering="NONE"
	side="BOTH"