modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="iceberg"
version="${file.jarVersion}"
displayName="Iceberg"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/520110"
logoFile="icon.png"
authors="Grend"
description="A library containing events, helpers, and utilities to make modding easier."

[[dependencies.iceberg]]
	modId="forge"
	mandatory=true
	versionRange="[40.1.6,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.iceberg]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="NONE"
	side="BOTH"